name: Generate Podcast Feeds
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chackout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: armin-ghaseminejad/podcast-generator@main
      
